### ISSUE TITLE
Does not work on macOS (unless browser is started from terminal)

### ISSUE THREAD

**Issue by jceloria** [dannyvankooten/browserpass#13]
browserpass 0.1.2
Firefox: 50.0.2
Chrome: Version 54.0.2840.98 (64-bit)
macOS: 10.12.1-x86_64
```
$─► brew info pass
pass: stable 1.6.5 (bottled), HEAD
Password manager
https://www.passwordstore.org/
/usr/local/Cellar/pass/1.6.5_1 (27 files, 113.1K) *
  Poured from bottle on 2016-11-14 at 02:22:01
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pass.rb
==> Dependencies
Required: pwgen ✔, tree ✔, gnu-getopt ✔
==> Requirements
Required: gpg2 ✔
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
```
I installed the browser extensions from the Chrome webstore and Firefox, downloaded browserpass-darwinx64.zip and ran install.sh, selected both Chrome and Firefox and restarted both browsers. When I attempt to use browserpass I'm just presented with the message "Error talking to Pass"

I am able to run pass from the command line without issue:
```
$─► pass Games/ea.com | sed -e '1 s/^.*$/none-yo/g' -e 's/^\(login: \).*/\1 business/g'
none-yo
---
login:  business
url: https://www.ea.com
```

Am I missing something?

**Comment by emersion** [comment]
Can you start Chrome from the command line and see if an error message is printed?

**Comment by jceloria** [comment]
Sure, thank you for the response!

[28164:60163:1211/113143:ERROR:native_process_launcher.cc(137)] Can't find manifest for native messaging host com.dannyvankooten.browserpass

**Comment by jceloria** [comment]
Sorry, I had forgotten that I removed the binary, I reinstalled and got the following:
LaunchProcess: failed to execvp:
/Users/jceloria/Applications/browserpass-darwinx64/browserpass-darwinx64

I then checked the path to the binary and it was not executable, I changed the permissions and things are working as expected for Chrome, thank you and my apologies for not catching something so simple.

**Comment by jceloria** [comment]
I get the following with Firefox:

1481480385534	addons.webextension.browserpass@dannyvankooten.com	WARN	Loading extension 'browserpass@dannyvankooten.com': Reading manifest: Error processing author: An unexpected property was found in the WebExtension manifest.
1481480385542	addons.webextension.browserpass@dannyvankooten.com	WARN	Please specify whether you want browser_style or not in your browser_action options.

**Comment by jceloria** [comment]
I get the following with Firefox:

1481480385534	addons.webextension.browserpass@dannyvankooten.com	WARN	Loading extension 'browserpass@dannyvankooten.com': Reading manifest: Error processing author: An unexpected property was found in the WebExtension manifest.
1481480385542	addons.webextension.browserpass@dannyvankooten.com	WARN	Please specify whether you want browser_style or not in your browser_action options.

**Comment by emersion** [comment]
Does it work with Firefox? These are just warnings.

**Comment by jceloria** [comment]
No, I get the same error talking to pass message. The only other message I
get in the console I get when I click in different parts of the window:

2016-12-12 14:10:55.584 firefox[32596:10486428] IMKInputSession
presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : *NO*
NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain
Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection
from pid 0}, com.apple.inputmethod.EmojiFunctionRowItem

Its still working fine in Chrome.

**Comment by emersion** [comment]
It seems that native messaging errors are not displayed in the terminal by Firefox. Can you check the [browser console](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging#Viewing_log_output) instead?

Source: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging#Troubleshooting

**Comment by jceloria** [comment]
The path to the binary was incorrect, I re-ran the install script and
restarted Firefox, I do get a message saying that a password has not been
found for the page I'm on. When I attempt to search I get the Error talking
to Pass message with the following in the console:

The character encoding of the HTML document was not declared. The document
will render with garbled text in some browser configurations if the
document contains characters from outside the US-ASCII range. The character
encoding of the page must be declared in the document or in the transfer
protocol.  content.html
File closed  NativeMessaging.jsm:246
Searching for: Logz  script.js:99:3
Error: File closed  script.js:103:7
File closed

It appears as if I can't search using Chrome either.

**Comment by dannyvankooten** [comment]
(Sorry for being so absent, I'm in the midst of my holiday and with limited internet. @emersion thanks for dropping by and helping out! I hope to be back in two weeks to work out some of these issues if needed & @emersion's PR.)

**Comment by Cadair** [comment]
fwiw, I am getting the same errors in the debug console as @jceloria. I am using Arch Linux and Firefox 50.0.1.

**Comment by emersion** [comment]
@Cadair How did you install browserpass?

@jceloria Can you check `debug.log`?

@dannyvankooten No problem, thanks for your work!

**Comment by Cadair** [comment]
I installed the binary from the AUR package and the plugin from the firefox plugins "store"

**Comment by emersion** [comment]
@Cadair The binary in the AUR doesn't work because the latest release doesn't include a fix (#14). You can install [browserpass-git](https://aur.archlinux.org/packages/browserpass-git/) instead.

**Comment by Cadair** [comment]
I seem to get a slightly different version of not working now.

```
Searching for: amazon.co.uk  script.js:99:3
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.  content.html
File closed  NativeMessaging.jsm:246
	_startRead/this.readPromise< resource://gre/modules/NativeMessaging.jsm:246:9
	loadExtensionInfo jar:file:///home/stuart/.mozilla/firefox/23btrlrk.default/extensions/%7B1EB88DA7-4F70-4E70-923F-810E4F0C9FDF%7D.xpi!/kango/loader.js:1:286
	<anonymous> chrome://kango-1eb88da7-4f70-4e70-923f-810e4f0c9fdf/content/includes/content_loader.js:1:1040
	PanelUI.showSubView/panelRemover< chrome://browser/content/customizableui/panelUI.js:364:9
	bound  self-hosted
TypeError: this.cloneScope is null[Learn More]
```

**Comment by jceloria** [comment]
I've updated to v1.0.2 and now I'm receiving a different message:

Firefox:
```
Error: File closed  script.js:127:7
stderr output from native app com.dannyvankooten.browserpass: 2017/01/18 09:38:06 exec: "pass": executable file not found in $PATH
```

Chrome:
Works fine when I launch from the command line, times out when I start it from the launcher (I can only assume its having the same trouble)

```
$─► which pass; uname -a; echo; cat /etc/paths
/usr/local/bin/pass
Darwin ip-192-168-0-246.ec2.internal 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,4 Darwin

/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

**Comment by dannyvankooten** [comment]
I have good hopes that 343722bee3bfff3739caceee74d2a543505d8cd5 will fix this issue @jceloria, can you please try building the Browserpass binary from that commit?

**Comment by jceloria** [comment]
Thanks for looking into this... Unless I'm doing something wrong during the build, it still seems to be a issue:

```
$─► rm -rf $GOPATH browserpass/; echo -e "\nCloning repository: " && git clone https://github.com/dannyvankooten/browserpass.git && go get github.com/mattn/go-zglob && cd browserpass/ && rm -f browserpass.go && curl -O https://raw.githubusercontent.com/dannyvankooten/browserpass/343722bee3bfff3739caceee74d2a543505d8cd5/browserpass.go && echo -e "Done checking out latest release...\n" && echo "Current git diff: " && git diff --shortstat && echo -e "\nContinue building/installing: " && make browserpass-darwinx64 && mv -f browserpass-darwinx64 ~/Applications/browserpass-darwinx64 && cd - && echo "Done."

Cloning repository:
Cloning into 'browserpass'...
remote: Counting objects: 503, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 503 (delta 20), reused 0 (delta 0), pack-reused 452
Receiving objects: 100% (503/503), 421.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (292/292), done.
Done checking out latest release...

Current git diff:
 1 file changed, 23 insertions(+), 28 deletions(-)

Continue building/installing:
env GOOS=darwin GOARCH=amd64 go build -o browserpass-darwinx64
/Users/jceloria/repos
Done.
```

I have restarted both Chrome and Firefox and still just get a spinning circle trying to fill in a password box:
<img width="284" alt="screen shot 2017-02-10 at 9 06 16 am" src="https://cloud.githubusercontent.com/assets/1354592/22831562/685d7216-ef70-11e6-936a-495ef271cf6b.png">

**Comment by jceloria** [comment]
Apparently now, its no longer the pass binary but the gpg binary (for which I also installed via homebrew):

```
stderr output from native app com.dannyvankooten.browserpass: [Browserpass] 2017/02/10 09:12:27 Password store is /Users/jceloria/.password-store
stderr output from native app com.dannyvankooten.browserpass: [Browserpass] 2017/02/10 09:12:27 Searching for linkedin.com
stderr output from native app com.dannyvankooten.browserpass: [Browserpass] 2017/02/10 09:12:30 Password store is /Users/jceloria/.password-store
stderr output from native app com.dannyvankooten.browserpass: [Browserpass] 2017/02/10 09:12:30 Reading password file /Users/jceloria/.password-storeEmployment/linkedin.com.gpg
stderr output from native app com.dannyvankooten.browserpass: [Browserpass] 2017/02/10 09:12:30 exec: "gpg": executable file not found in $PATH
Error: File closed  script.js:127:7
login is undefined
```

**Comment by dannyvankooten** [comment]
It seems to be that Firefox is running as a different user (or at least running the binary as a different user) which doesn't have the brew linked libraries in its `$PATH` variable. Does it work if you invoke Firefox from the command-line?

**Comment by jceloria** [comment]
```
$─► echo $(whoami && id -u) && ps -efw | awk '$0~/Firefox/ && $0!~/awk/ {print $1, $8}'
jceloria 501
501 /Applications/Firefox.app/Contents/MacOS/firefox
501 /Applications/Firefox.app/Contents/MacOS/plugin-container.app/Contents/MacOS/plugin-container
```

Previously, it did work before when starting from the cli, but now its not:
```
1486743986177	addons.webextension.browserpass@dannyvankooten.com	WARN	Loading extension 'browserpass@dannyvankooten.com': Reading manifest: Error processing author: An unexpected property was found in the WebExtension manifest.
console.info: **** loading module resource://donottrackplus-at-abine-dot-com/data/global.js
console.debug:
  initialized AbineContentPolicy
Extension error: TypeError: login is undefined moz-extension://025db812-7d7c-ab4a-903e-3ae8aab0300c/script.js 167
[[Exception stack
fillLoginForm@moz-extension://025db812-7d7c-ab4a-903e-3ae8aab0300c/script.js:167:45
getLoginData/<@moz-extension://025db812-7d7c-ab4a-903e-3ae8aab0300c/script.js:131:5
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:62:129
runSafeWithoutClone@resource://gre/modules/ExtensionUtils.jsm:255:38
wrapPromise/</<@resource://gre/modules/ExtensionUtils.jsm:438:15
withLastError@resource://gre/modules/ExtensionUtils.jsm:378:14
wrapPromise/<@resource://gre/modules/ExtensionUtils.jsm:432:11
]]
```

**Comment by seanfarley** [comment]
For the Mac, it's nothing to do with the user id. There's no easy way to set environment variables for applications launched via the dock or finder. There are a few launchd commands but they're dubious at best (and I haven't been able to get one to reliably work).

The easiest solution would be to fallback to checking common locations (e.g. `/opt/local/bin` (MacPorts), `/usr/local/bin` (Homebrew), etc). If I was better at go, I would submit a PR, but alas.

**Comment by johnimorris** [comment]
Hi guys, I am suffering from this too, on my Mac, but found a small workaround.  While not ideal may help others to get it working until a proper solution can be found.

For me, it ended up being 2 things.  The PATH didn't include /usr/local/bin, and since I run the curses gpg-agent, I had to make sure the GPG_AGENT_INFO and GPG_TTY environment variables were set.  To make this happen:

-  I wrapped the browserpass-darwinx64 executable with a script I called "browserpass-wrapper". 
- I changed the ~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts/com.dannyvankooten.browserpass.json to call my browserpass-wrapper instead.

- The browserpass-wrapper script looks like this:
#############################
#!/bin/bash

if [ -f "${HOME}/.gpg-agent-info" ]
then
    source ${HOME}/.gpg-agent-info
    export GPG_AGENT_INFO
fi
export GPG_TTY="$(tty)"
export PATH="$PATH:/usr/local/bin"
/Users/johnm/Projects/browserpass_binary/browserpass-darwinx64 "$@"
exit $?
###############################

The above script assumes I have a gpg agent running, writing its environment setting to ~/.gpg-agent-info.   

Also, note, while the above script is run with no tty, setting GPG_TTY="$(tty)" makes GPG_TTY the value "not a tty", and it still seems to satisfy the gpg-agent.

Also, of course change the path of browserpass-darwinx64 to where ever you have it.

Hope this helps others, or paves the way to a better solution.

**Comment by wilbowma** [comment]
FYI, I was having this issue as well, until I installed the native helper version 1.0.4.r0.f34c1c3-1. That solved it.
Firefox 52
Pass 1.7.1
Browerpass 1.0.3
ArchLinux

**Comment by joyarzun** [comment]
@johnimorris It works! Just remember give it chmod u+x to browserpass-wrapper

**Comment by SamHH** [comment]
@johnimorris No luck for me unfortunately. Same errors as I mentioned in the other issue: https://github.com/dannyvankooten/browserpass/issues/28#issuecomment-281067882

I guess my issue is different then?

**Comment by tverlaan** [comment]
@johnimorris thanks for the workaround!

**Comment by compuguy** [comment]
@johnimorris @SamHH @tverlaan Didn't get workaround working. Could this be related to using GPGTools for gpg?

**Comment by maximbaz** [comment]
I'd like to follow-up on this issue and ask you, do you think there is something actionable we could do to fix the issue, and is it actually something that needs to be fixed in browserpass?

As I understand, the issue is that GUI applications on macOS do not inherit custom environment variables when being started. I'm not a Mac user myself, but this would sound extremely suspicious to me if every single macOS application is expected to handle undefined environment variables. 

In Linux for example, it is user's responsibility to [make environment variables accessible to GUI apps](https://wiki.archlinux.org/index.php/Environment_variables#Graphical_applications). 

I've also seen application launchers fixing $PATH, with the idea (as I understand it) to fix $PATH in all application started by that launcher (an example would be [Cerebro launcher](https://github.com/KELiON/cerebro/), which is using [fix-path](https://www.npmjs.com/package/fix-path) library).

That's why I'm asking your advice if it is browserpass that needs to be fixed, or an application launcher, or some kind of configuration file like `.xinit` on Linux.

**Comment by inferiorhumanorgans** [comment]
https://github.com/electron/electron/issues/550

**Comment by guicapanema** [comment]
@maximbaz using Cerebro to launch firefox works for me!

**Comment by troelsh** [comment]
I couldn't make the wrapper script work, might be me but i found an alternate solution that sort of works. I created a launcher for chrome with automater it basically launches chrome and export the "correct" path first.

![screen shot 2017-09-26 at 15 28 36](https://user-images.githubusercontent.com/2182341/30862831-95698b38-a2cf-11e7-97ad-34d78f307bd2.png)

![screen shot 2017-09-26 at 15 30 25](https://user-images.githubusercontent.com/2182341/30862848-a3e1750e-a2cf-11e7-9c3f-50fbb77e5af0.png)

`export PATH=$PATH:/usr/local/bin
open -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome $1`

I however strongly believe in having this set more natively for chrome so it uses the same path as i use in my terminal. I don't currently have any ideers on how to do this or how to make sure this works in browserpass as it is not a problem on other OS?

**Comment by maximbaz** [comment]
Well, on Linux it also doesn't work _out of the box_, but it is [described in the Wiki](https://wiki.archlinux.org/index.php/Environment_variables#Graphical_applications), why and how to adjust the Linux configuration so that all graphical applications have access to environment variables.

That being said, I don't think it is something we can/should solve in browserpass (I'm happy to see a PR that proves me wrong 🙂). Until then, I'm considering to close this issue by creating a FAQ entry where I would list the discovered workarounds.

**Comment by maximbaz** [comment]
Has anyone tried [this](https://serverfault.com/q/16355) (or [this](https://stackoverflow.com/a/26586170) for Yosemite and later)?

**Comment by troelsh** [comment]
@maximbaz i will try it tomorrow when i have the time and get back to you.

**Comment by troelsh** [comment]
on macOS Sierra v10.12.6 i had some success with the following command:

`sudo launchctl config user path $PATH`

![screen shot 2017-09-27 at 08 16 35 1](https://user-images.githubusercontent.com/2182341/30898647-9704b98a-a35c-11e7-82eb-e8a4a3400539.png)

Upon restart OSX asks if you want to reopen windows if you select yes it does not work, if you however opt out of that. When you open chrome from Dock it loads with the right path and browserpass works. Now i don't know i the reopening of windows for some reason uses another launcher or maybe it runs prematurely of the user config being set. Still not a 100% solution but better than the automator "solution".

**Comment by braderhart** [comment]
Tried the methods you suggested on Sierra 10.12.6 and still no luck for me. Wondering if it has to do with:

https://www.gnupg.org/faq/whats-new-in-2.1.html#autostart

**Comment by troelsh** [comment]
@maximbaz did you try what i wrote?

Offcourse it is implicit that the $PATH holds the path to /usr/local/bin if not the correct command is:

> sudo launchctl config user path $PATH:/usr/local/bin

**Comment by maximbaz** [comment]
@troelsh unfortunately I don't have a Mac to try any of the ideas posted here, I'm relying on you guys to test every discovery we make.

Let's try something else. The attached archive has a custom binary that does not rely on $PATH, but uses a hardcoded full path `/usr/local/bin/gpg` and `/usr/local/bin/gpg2`. This is not a proper fix (for example, on my Linux the path is `/usr/bin/gpg` and /usr/bin/gpg2`), but if you try this binary and tell me that it works for you, we will know for sure that the only problem here is the unknown path to `gpg` binary, and not the use of sockets since gpg 2.1.

@troelsh, @braderhart - could you try it now? Replace the binary with the attached file, and start your browser as usual, without any workarounds, and tell me if it works.

[browserpass-darwinx64.zip](https://github.com/dannyvankooten/browserpass/files/1338238/browserpass-darwinx64.zip)

**Comment by braderhart** [comment]
@maximbaz Thanks for working on this and I'm happy to help out. I tried the new binary and still no luck. I can see my passwords, but it won't fill them when opened from the Dock.

**Comment by maximbaz** [comment]
Let's see if that binary will work for those who use $PATH workarounds...

Just to confirm, could you check the result of `$ which gpg` and `$ which gpg2`, do they point to `/usr/local/bin/gpg`?

**Comment by braderhart** [comment]
```
$ which gpg
/usr/local/bin/gpg
$ which gpg2
$
$ launchctl getenv GPG_TTY
/dev/ttys000
$ sudo launchctl getenv GPG_TTY
/dev/ttys000
$ launchctl getenv PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
$ sudo launchctl getenv PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

**Comment by braderhart** [comment]
@maximbaz Good news, I got it working with your latest binary! I did, however, have to install the pinentry-mac app to get a password prompt. I do not get the same results using the previous binary, but I will keep trying, unless you may understand why.

The steps are:
```
brew install pinentry-mac
echo 'pinentry-program /usr/local/bin/pinentry-mac' >> ~/.gnupg/gpg-agent.conf
gpgconf --kill gpg-agent
```

**Comment by maximbaz** [comment]
When you start browser from terminal and everything supposedly works even on the officially released binaries, what kind of password prompt do you see? In other words, if you don't have pinentry-mac, what app is being used to ask you for the password?

**Comment by braderhart** [comment]
@maximbaz I believe it is just /usr/local/pinentry which runs in the terminal.

I tried changing the `pinentry-program` to `/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal /usr/local/bin/pinentry' without success, however `pinentry-mac` works.

**Comment by maximbaz** [comment]
Okay, having to ask to install `pinentry-mac` is not too bad. I was afraid that browserpass doesn't work because of all environment variables are missing, but according to the previous workarounds and your experiments with this test binary, it looks that only $PATH is needed, and only to find the location of `gpg` binary that we call from the code. I'll adjust the code, so that if `gpg` is not in the $PATH, it will attempt to find it in most common directories (like `/usr/local/bin`). That should hopefully fix this issue after all. Stay tuned, I'll ask you for one more testing 🙂

**Comment by braderhart** [comment]
@maximbaz Agreed and glad that I was able to help some. Thanks for the quick updates.

**Comment by maximbaz** [comment]
@braderhart and anyone interested, please try this new binary and let me know if it solves this issue.
 
[browserpass-darwinx64.zip](https://github.com/dannyvankooten/browserpass/files/1338766/browserpass-darwinx64.zip)

**Comment by maximbaz** [comment]
For those of you keen to look at the code change, see #159.

**Comment by braderhart** [comment]
@maximbaz Latest one works fine without any changes to the $PATH as long as pinentry-mac is used.

**Comment by maximbaz** [comment]
Thanks! I'll leave the PR open for a day or two, to let more people try before closing this issue and claiming that it has been fixed. 

Planning to make a new release on Friday, and also finally upload the browser extensions in the Webstores (under a new name, unfortunately, due to #117).

**Comment by troelsh** [comment]
@braderhart i believe if you have installed GGP Suite from https://gpgtools.org/ then it can use the os keychain for automatic pin-entry you have to turn that off in System Preferences -> GPG Suite. If you have done that then it will use pinentry-mac for every use of browser pass. Everything installed via the GPG Suite.

@maximbaz i will give it a try but i don't know if i can unfix my path now that i have "fixed it". I can try and restore it to something basic. And test your binary.

Too bad about the name on the extension store but i guess we can live with MAXBrowserPass 🦄 . Or maybe Browserpass Community Edition (browserpass-ce).

PS. Kids pfffff 💃

**Comment by compuguy** [comment]
The test build from @maximbaz works great with GPGtools.

**Comment by siwan05** [comment]
I can also confirm that the test build from @maximbaz works with GPGtools! 👍

**Comment by maximbaz** [comment]
At last, I'm happy to announce - fixed in [v2.0.0](https://github.com/dannyvankooten/browserpass/releases/tag/2.0.0)! 🎉

**Comment by mandarvaze** [comment]
Installed v2.0.0 (and browserpass-ce, and pinentry-mac)
All is well !!!
👏

**Comment by SamHH** [comment]
Still not working for me out of the box...

macOS 10.12.6, Vivaldi 1.12.955.36, browserpass-ce 2.0.0.

It can find my password files, but if I click on one nothing happens, the extension popup just closes.

**Comment by maximbaz** [comment]
Are you using the GPGtools like others mentioned above?

**Comment by braderhart** [comment]
You can also install pinentry-mac using brew, and then add it to the pinentry-program in the gpg-agent.conf file.
________________________________

**Comment by mandarvaze** [comment]
@SamHH Does it work for Firefox and/or Chrome ? Could be Vivaldi specific issue ?

**Comment by SamHH** [comment]
I followed @braderhart's instructions which did get a GPG dialog to pop up successfully. Unfortunately after entering my password and hitting enter nothing is happening. I've tested this in both Vivaldi and Chrome.

**Comment by maximbaz** [comment]
Could it be a specific website that is affected, i.e. can you repro the bug on github.com/login ?

#164 would help a lot in such investigations... 🙂

**Comment by SamHH** [comment]
Aha, okay, it is working. I've not actually been able to use Browserpass before due to the above issues so I didn't know what to expect, the autofill works surprisingly well! 😄  So my issue here is resolved, thank you all!

Outside the scope of this ticket, but are there plans to allow you to view the contents of the decrypted password file a la LastPass, rather than only click to autofill? I know there are a handful of websites I frequent where for one reason or another that's necessary, and it'd be annoying to have to pop open a terminal each time.

**Comment by maximbaz** [comment]
#105 will probably make you happy @SamHH.

However I'll use this opportunity to stress out again, our goal is to mitigate phishing attacks by making autofill algorithm work as perfect as possible. There have been substantial improvements implemented recently thanks to people who share specific examples of websites where autofill is broken, I urge everyone to share more examples if you happen to stumble upon such.

**Comment by Sophia-Gold** [comment]
I'm also getting the "Error: Native host has exited" message from Chrome 55 and came here from https://github.com/dannyvankooten/browserpass/issues/28 which didn't seem as OS specific

I'm on NixOS, although for some reason it couldn't locate the Browserpass packaged on channel nixos-17.03 so I installed it first from the Chrome web store and then later with your install script to see if that would fix the native messaging problem (although they're currently both the same version).

The problem persists if I launch Chrome from root. The only other thing I can think of is I haven't added usernames in my password file (either with a backslash on the pass-name or as a separate login), but even if that means Browserpass won't decrypt any passwords it shouldn't affect native messaging.

Any ideas?

**Comment by maximbaz** [comment]
Since your issue seems different from this one (different OS, running browser from terminal doesn't solve the problem), could you please create a new ticket and fill out the issue template? Please also mention at which stage you see this error, immediately after clicking on browserpass icon it toolbar or after you select a password entry.

Generally "Error: Native host has exited" means that the host app was discovered, but it crashed while performing its operation. 

The structure of your pass files shouldn't be an issue, but try creating one with a fake username just to test this idea.

**Comment by raxod502** [comment]
I have created a script [`patch-macos-app.zsh`](https://github.com/raxod502/radian/blob/9e776b7811d87828fb081dae6b8ead52504877eb/scripts/patch-macos-app.zsh) which can be used to modify any macOS application so that it sources `~/.profile` on launch (without the need to launch through a wrapper script, and presumably also so that it works after a restart with the "reopen windows" option). Having put my `$PATH` and `gpg-agent` configuration in `~/.profile`, applying this script to Google Chrome makes Browserpass work for me:

```
% ./patch-macos-app.zsh 'Google Chrome' 'Google Chrome' 'Google Chrome Core' --patch
Patched successfully: /Applications/Google Chrome.app
```

**Comment by davidbarratt** [comment]
To get this to work I had to:
```
brew install pinentry-mac
echo "pinentry-program /usr/local/bin/pinentry-mac" >> ~/.gnupg/gpg-agent.conf
```

Perhaps this should be added to the install instructions?
