### ISSUE TITLE
Not pasting in Firefox / Mac

### ISSUE THREAD

**Issue by mcnesium** [dannyvankooten/browserpass#71]
When starting Firefox using `open -a firefox` on the command line, browserpass is able to talk to pass (finds entry when searching for it), but then it does not paste the login data to the form. The loading sign just keeps rotating for ever… 

Firefox 53.0 (64-Bit) / Mac
browserpass 1.0.3

**Comment by dannyvankooten** [comment]
If you go to Firefox > Extensions > Debug Add-ons (wheel in top right) and then hit the "Debug" button next to Browserpass, do you see any errors in the debug console?

**Comment by mcnesium** [comment]
![bildschirmfoto 2017-05-04 um 09 39 27](https://cloud.githubusercontent.com/assets/476060/25694523/51477556-30af-11e7-9008-1d33bd5480ee.png)

**Comment by mcnesium** [comment]
It did work in some Firefox 53.0.* version and then stopped working again in Firefox 54 :(

**Comment by mcnesium** [comment]
still the same in Firefox 55.0.3

**Comment by maximbaz** [comment]
This looks awfully lot like #128, /cc @tsnieman.

I wonder if you guys are having some unusual gpg configuration?

@mcnesium could you try to clone the current `master`, do `make js` and load an unpacked extension from sources, instead of using a packed extension, and seeing if the issue reproduces and possibly sharing the error logs again?

**Comment by tsnieman** [comment]
> I wonder if you guys are having some unusual gpg configuration?

Could be! Let's dissect my config.

Using: `Ubuntu 17.04 + GNOME shell`

```# ~/.zshrc (I use zsh instead of bash)
# Use gpg2 instead of gpg.
alias gpg=gpg2

# Configure the current TTY for GnuPG client.
export GPG_TTY=$(tty)
export SSH_AUTH_SOCK=~/.gnupg/S.gpg-agent.ssh

# OpenPGP applet support for YubiKey NEO
if [ ! -f /tmp/gpg-agent.env ]; then
  killall gpg-agent;
  eval $(gpg-agent --daemon --enable-ssh-support > /tmp/gpg-agent.env);
fi
. /tmp/gpg-agent.env

# Turn off ssh-agent inside gnome-keyring-daemon:
if [[ $(gconftool-2 --get /apps/gnome-keyring/daemon-components/ssh) != "false" ]]; then
  gconftool-2 --type bool --set /apps/gnome-keyring/daemon-components/ssh false
fi
```

`SSH_AUTH_SOCK=~/.gnupg/S.gpg-agent.ssh` doesn't make much sense to me, as `S.gpg-agent.ssh` as a file does not exist.

Aside from that, to be fair, I only have a loose grasp on what either of the above `if`s are doing. I seem to get my best results with this whole setup if both are in my `.zshrc` though.

---

```
# ~/.gnupg/gpg-agent.conf
pinentry-program /usr/bin/pinentry-gnome3
enable-ssh-support
keep-display
keep-tty
default-cache-ttl 3600
max-cache-ttl 7200
scdaemon-program /usr/lib/gnupg/scdaemon
sh
homedir ~/.gnupg
```
unclear on purpose of `sh` above, but the rest seem straightforward enough

---

```# ~/gnupg/gpg.conf
default-key 0x1640A8B61F6FD0E5
no-emit-version
no-comments
keyid-format 0xlong
with-fingerprint
list-options show-uid-validity
verify-options show-uid-validity
use-agent
fixed-list-mode
charset utf-8
personal-cipher-preferences AES256 AES192 AES CAST5
personal-digest-preferences SHA512 SHA384 SHA256 SHA224
cert-digest-algo SHA512
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
```

---

Common echos I see online:

```
% echo $GPG_TTY
/dev/pts/1

% echo $GPG_AGENT_INFO
<does not return anything>

% echo $SSH_AUTH_SOCK 
/run/user/1000/gnupg/S.gpg-agent.ssh
```

Not sure what these are necessarily "supposed to" return.

---

Wondering if @mcnesium has anything similar in his setup that might be causing him issues. I got here by followiong a buncha old guides, written for debian, different versions of gpg, mac os, or some other variant that doesn't fit my "Ubuntu + GNOME + Yubikey" setup.

**Comment by maximbaz** [comment]
Wow you have a lot of stuff 🙂 Nothing stands out as particularly suspicious to me, but out of curiosity, have you actually tried removing all that, rebooting and just going with the default configuration? I also have some gpg configuration, but I didn't _need_ any of it to use browserpass, it just worked from day one with no configuration from my side.

**Comment by guicapanema** [comment]
Hi everyone! I've just moved to pass and am trying to get this extension working.

@maximbaz I have the following config files in `~/.gnupg`, all empty, as a result of a default installation on macOS 10.12.6:
- S.gpg-agent
- S.gpg-agent.browser
- S.gpg-agent.extra
- S.gpg-agent.ssh

I am using Firefox 55.0.3 and getting the same error (login is not defined).

**Comment by maximbaz** [comment]
There was this PR today which is relevant to Firefox: https://github.com/dannyvankooten/browserpass/pull/137

I've just published a release v1.0.12 that includes this PR, could you try it out?

**Comment by guicapanema** [comment]
It's not loading infinitely anymore (clicking the desired login now closes the addon popup). However, I'm still getting login undefined:

<img width="1012" alt="captura de tela 2017-09-17 as 11 05 20" src="https://user-images.githubusercontent.com/8330306/30521586-3ff37e5e-9b98-11e7-863d-60f1d3187246.png">

**Comment by maximbaz** [comment]
So we are back to the `login undefined`.

Is it possible to debug the background.js in Firefox? The problem is happening on [this line](https://github.com/dannyvankooten/browserpass/blob/802b7e3376a62468f7b6f2aaff334973f86dee3a/chrome/background.js#L23), where `response` is undefined on your side. It would be really nice if you could inspect all the values around there in debug mode, inspect `chrome.runtime.lastError`, maybe _something_ will give us a hint...

In Chrome, this is how you debug the background.js:

![image](https://user-images.githubusercontent.com/1177900/30521792-6590b686-9bc5-11e7-9fa2-81d0de4105f0.png)

**Comment by guicapanema** [comment]
I'm doing my best here, but this is all quite new to me, so please bear with me @maximbaz .

This is what I have at line 18:
<img width="495" alt="line18" src="https://user-images.githubusercontent.com/8330306/30522026-fe9eede6-9b9f-11e7-95ce-b289b8b7c63d.png">

At line 23, hovering over the objects:

<img width="393" alt="captura de tela 2017-09-17 as 11 58 31" src="https://user-images.githubusercontent.com/8330306/30522034-1970b62c-9ba0-11e7-900c-aef451ce9355.png">
<img width="366" alt="captura de tela 2017-09-17 as 11 58 36" src="https://user-images.githubusercontent.com/8330306/30522036-1d20db30-9ba0-11e7-8b95-b84cfcc6bb29.png">
<img width="364" alt="captura de tela 2017-09-17 as 11 58 43" src="https://user-images.githubusercontent.com/8330306/30522038-2284c9c4-9ba0-11e7-90e5-8939d8b95a5b.png">

Which I'm guessing is not very helpful, right?

I tried hovering over the objects at line 19 as well:
<img width="403" alt="captura de tela 2017-09-17 as 12 00 24" src="https://user-images.githubusercontent.com/8330306/30522055-44ff951a-9ba0-11e7-9aad-1571e1c0c728.png">
<img width="333" alt="captura de tela 2017-09-17 as 12 00 07" src="https://user-images.githubusercontent.com/8330306/30522057-4680ce54-9ba0-11e7-9ee7-641e94834f57.png">

**Comment by maximbaz** [comment]
Thanks! This is the most valuable piece of information:

![image](https://user-images.githubusercontent.com/8330306/30522038-2284c9c4-9ba0-11e7-90e5-8939d8b95a5b.png)

So we know that _some_ kind of runtime error is happening when communicating with the host application, and that is why `response` is null. Unfortunately the error is very vague... "An unexpected error occurred" - come on, Firefox!

I'm honestly not sure how to go from here. Could you try maybe some of the newer FF versions, like FF Nightly (I think it is v57 now)? I'm hoping that FF developers added some error description in the newer versions.

**Comment by guicapanema** [comment]
I did that and got the same message:

<img width="355" alt="captura de tela 2017-09-17 as 15 41 10" src="https://user-images.githubusercontent.com/8330306/30523826-e17b60e0-9bbe-11e7-89d5-8c7081c32394.png">

But it did give me a stack:
Async*onMessage@moz-extension://5d159489-c4c9-c246-b57d-cb8cdf03aa2e/background.js:19:5\n"

Which I think is also not very helpful, right? :(

**Comment by maximbaz** [comment]
Not really :(

Could you describe precisely the steps of how you installed browserpass?

**Comment by guicapanema** [comment]
First I followed the installation instructions (installed the host app without `sudo`, got the extension from mozilla's web store). That gave me the error I first reported.

Since then, I've tried installing the host app with `sudo` & have been downloading the extension from the releases page (`firefox.zip`) and loading it via Extensions > Debug extensions > Load temporary addon and selecting the manifest.json file in the unzipped folder, which is what seemed to get it to load here.

**Comment by maximbaz** [comment]
Thanks, I'm not used to Firefox, I have just installed it and I was searching on how to load the extension from the releases page, since the extension on web store is outdated. 

Your hint on using `Extensions > Debug extensions > Load temporary addon` did the trick.

But, fortunately or unfortunately, I can't reproduce your error, it just works for me. I also installed the host app from the releases page without `sudo`.

The only difference so far is that I'm on Linux and you are on Mac, but maybe there is something else that we haven't discovered yet...

Please post the results of these commands:

```
$ ls -al /Library/Application Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json
$ cat /Library/Application Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json

$ ls -al $HOME/Library/Application Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json
$ cat $HOME/Library/Application Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json
```

**Comment by guicapanema** [comment]
`$ ls -al /Library/Application\ Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json`
-rw-r--r--  1 root  admin  282 17 Set 12:05 /Library/Application Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json

`$ cat /Library/Application\ Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json`
{
  "name": "com.dannyvankooten.browserpass",
  "description": "Browserpass binary for the Firefox extension",
  "path": "/Users/capanema/Downloads/browserpass-darwinx64/browserpass-darwinx64",
  "type": "stdio",
  "allowed_extensions": [
    "browserpass@dannyvankooten.com"
  ]
}

`$ ls -al $HOME/Library/Application\ Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json`
-rw-r--r--  1 capanema  staff  282 17 Set 10:55 /Users/capanema/Library/Application Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json

`$ cat $HOME/Library/Application\ Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json`
{
  "name": "com.dannyvankooten.browserpass",
  "description": "Browserpass binary for the Firefox extension",
  "path": "/Users/capanema/Downloads/browserpass-darwinx64/browserpass-darwinx64",
  "type": "stdio",
  "allowed_extensions": [
    "browserpass@dannyvankooten.com"
  ]
}

**Comment by maximbaz** [comment]
I don't think you are supposed to have both files, maybe this is the issue... For a non-sudo installation, only the second file should exist. Try to remove the first file:

```
$ rm /Library/Application\ Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json
```

And then let's double-check that you have binary in the correct place, please post the output of this:

```
$ ls -al /Users/capanema/Downloads/browserpass-darwinx64/browserpass-darwinx64
```

**Comment by guicapanema** [comment]
Yes, I checked that:

-rwxr-xr-x@ 1 capanema  staff  2948016 17 Set 15:48 /Users/capanema/Downloads/browserpass-darwinx64/browserpass-darwinx64

I think had both because I tried first without and then with sudo. Still no luck after removing the sudo one.

**Comment by maximbaz** [comment]
Thanks for double checking all this... So everything seems to be in order, except that it doesn't work 😕 

Could you try if extension works on Chrome, just out of curiosity? It will also tell us if the problem is within host app or specifically Firefox extension.

**Comment by guicapanema** [comment]
Well, that was my thinking as well, and I think it told us something new at least:

<img width="629" alt="captura de tela 2017-09-17 as 16 48 45" src="https://user-images.githubusercontent.com/8330306/30524328-25073768-9bc8-11e7-91b7-0a45c5d38956.png">

**Comment by maximbaz** [comment]
Huh, so it _also_ doesn't work in Chrome? Assuming you used extension from the release (and not webstore) and ran `./install.sh` for Chrome and everything installed correctly, now I'm curious if the problem is with the host app.

If you are not tired of doing experiments yet, let's do some more 🙂

One thing I want to try is to ask you to close Chrome and start it again from terminal. Maybe it will write some extra error logs in the terminal when you make an (unsuccessful) attempt to use the extension.

Another thing would be to try to compile the host app on your side. I'm wondering if maybe because I compile app for Mac on Linux, something is getting wrong with the binary. That is a bigger effort, see [CONTRIBUTING.md](https://github.com/dannyvankooten/browserpass/blob/master/CONTRIBUTING.md), the `You will need ...` and `To build` sections.

**Comment by guicapanema** [comment]
OK, so loading both Chrome and Firefox from the terminal makes it work!

Did the following: 

1. Opened Chrome by double-clicking the app. Installed extension. **Doesn't work.**
2. Opened Chrome from terminal (`$ open Google\ Chrome.app`). Did not reinstall the extension (used the one previously installed). **Works**

Same process, same results with Firefox. I remember seeing this in PassFF: https://github.com/passff/passff/issues/219

Maybe something related? Will try installing the host _only_ with sudo and get back here

**Comment by maximbaz** [comment]
Ah man... I saw this issue earlier and I didn't do 2+2 to realize it's the same issue! 

What you describe is exactly the #13, it is macOS related that $PATH and other environment variables are not defined in GUI apps. I actually posted a [question](https://github.com/dannyvankooten/browserpass/issues/13#issuecomment-329618176) in that thread asking if this is really an app problem (and whether we can do something about it), or it is a macOS / app launcher problem.

There is also a [workaround](https://github.com/dannyvankooten/browserpass/issues/13#issuecomment-316951512) posted that seems to work for people.

I made a guess there that [Cerebro launcher](https://github.com/KELiON/cerebro/) is solving this issue, but I haven't heard back on whether this is actually true. Do you want to test this, install Cerebro and see if extension works when you launch Chrome / FF from it? 

Let's continue discussion in that thread.

**Comment by maximbaz** [comment]
I would close it, but @tsnieman has posted above that he has the same issue on Linux - and that is surprising. 

So @tsnieman, if you could go through the same investigation steps as above, that would certainly be useful.

**Comment by guicapanema** [comment]
Nope, no luck, even with `sudo`. Removed all the files in both `/Library/Application\ Support/Mozilla/NativeMessagingHosts/` and `$HOME/Library/Application\ Support/Mozilla/NativeMessagingHosts/`. Re-installed host using `sudo ./install.sh`. 

Only works when opening FF from the command line.

**Comment by mcnesium** [comment]
Can confirm @guicapanema: I removed everything, installed v1.0.13 for Firefox, started it via `open -a Firefox` on the command line, then added the `manifest.json` as described via the debug view and voila it works. When starting Firefox via Alfred or by icon, it does not.

So I opened `~/Scripts/start-firefox.sh` in an editor and wrote

    #!/usr/bin/env bash
    source $HOME/.bashrc && open -a Firefox

in it. My Alfred is configured to find and execute `.sh` files, so when I type Fire… it finds that script as well. One could as well drag the script in the dock or whatever to use this instead of the original Firefox binary.

The best part about that workaround is, that it also works with v1.0.5 of the firefox plugin, that I installed via the `about:addons` view. So we can actually use the default installation method until that upstream issue is fixed :)

**Comment by maximbaz** [comment]
Not sure if that is the best part, as so many bug fixes and improvements have been merged since v1.0.5 😛

**Comment by mcnesium** [comment]
But the proposed way via debug view requires to re-add the plugin again after every start, so I find this more comfortable for everyday use. Why isn'T the plugin being updated on AMO anyway?

**Comment by maximbaz** [comment]
Agree. Reason: #117

**Comment by mcnesium** [comment]
I see, sorry for the noise :)

**Comment by maximbaz** [comment]
No worries :)

**Comment by maximbaz** [comment]
Seems like a code fix has been found in #13, and it supports many popular `/bin` directories, so should fix not only missing $PATH on Mac, but also on Linux. I'll close this bug, let's all follow #13 for updates.
